import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ButtonRow } from '../components/UI/atoms/ButtonRow/ButtonRow';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.home_header}>
        <content_box className={styles.content_box}>
          <left_items className={styles.left_items}>
            <header_info_box className={styles.header_info_box}>
              <h1 className={styles.h1}>Hello There,</h1>
              <h2 className={styles.h2}>
                I'm <span className={styles.span}>Deborah</span>
              </h2>
              <p className={styles.p}>
                A frontend developer with a passion for visuals
              </p>
              <line_div className={styles.line_div}></line_div>
              <button_array className={styles.button_array}>
                <button className={styles.blue_button}>About</button>
                <button className={styles.white_button}>About</button>
              </button_array>
            </header_info_box>
          </left_items>
          <right_items className={styles.right_items}></right_items>
        </content_box>
      </section>
      <section className={styles.subheading_container}>
        <subheading_left className={styles.subheading_left}>
          <subheading_left_bg
            className={styles.subheading_left_bg}
          ></subheading_left_bg>
        </subheading_left>
        <subheading_right className={styles.subheading_right}>
          <subheading_right_bg className={styles.box_border_gradient}>
            <subheading_right_bg_overlay
              className={styles.subheading_right_bg_overlay}
            ></subheading_right_bg_overlay>
          </subheading_right_bg>
        </subheading_right>
      </section>
    </div>
  );
}
